name: unified
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/      # 清华镜像 defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/  # 清华镜像 conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/      # 清华镜像 pytorch
  - defaults  # 兜底（防止镜像同步延迟）
dependencies:
  - python=3.9
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - scikit-learn=1.1.1
  - pandas=1.4.3
  - scipy=1.9.1
  - pip
  - pip:
      - wandb==0.13.1
      - hydra-core==1.2.0
      - omegaconf==2.2.3
      - nilearn==0.9.2
